### ISSUE TITLE
Поддержка IPv4

### ISSUE THREAD

**Issue by freeacetone** [zhoreeq/meshname#10]
Будет замечательно реализовать поддержку IPv4. Эти домены очевидно будут короче, а также расширят область практического применения протокола meshname фактически максимально и сделают meshnamed несравненным инструментом именованного сообщения без привычных серверов DNS.

**Comment by whoizit** [comment]
тебе следует разворачивать свои мысли, я не понял ни одной проблемы из тех проблем что ты озвучил

**Comment by zhoreeq** [comment]
Пока нет реальных юзкейсов, IPv4 добавлять не будем
