### ISSUE TITLE
ebuild for gentoo

### ISSUE THREAD

**Issue by Bogdan107** [zhoreeq/meshname#16]
Прошу описать инструкцию для сборки приложения без доступа к интернету.

В данный момент вызов make запускает систему сборки, которая динамически подгружает внешние модули, прежде чем начать компиляцию.

При доступе к интернету программа компилируется успешно.

Для интеграции в Gentoo, необходимо написать ebuild - сценарий сборки. Его особенность - сборка приложения в sandbox, в котором доступ в интернет весьма нежелателен.

Я не разбираюсь в Go, но хочу использовать meshname, используя штатные встроенные средства установки, а не добавляя программу в систему вручную.

Прошу описать какие файлы необходимо загрузить, куда их складывать в пределах каталога исходных кодов meshname и как пропатчить исходные файлы, чтобы make не нуждался в интернете для загрузки внешних модулей.

**Comment by zhoreeq** [comment]
Перед запуском make надо скачать все зависимости, тогда инет не нужен будет

https://stackoverflow.com/questions/32758235/how-to-get-all-dependency-files-for-a-program

Попробуй вариант `go get -d ./...`

**Comment by Bogdan107** [comment]
ebuild для Gentoo:

1) meshname-0.1.0.ebuild - сценарий сборки в системе portage (Gentoo):
```
# Distributed under the terms of the GNU General Public License v2 

EAPI="7"
inherit go-module

DESCRIPTION="Meshname, a universal naming system for all IPv6-based mesh networks, including CJDNS and Yggdrasil"
HOMEPAGE="https://github.com/zhoreeq/meshname"

EGO_SUM=(
    "github.com/gologme/log v1.2.0"
    "github.com/gologme/log v1.2.0/go.mod"
    "github.com/miekg/dns v1.1.27"
    "github.com/miekg/dns v1.1.27/go.mod"
    "golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2/go.mod"
    "golang.org/x/crypto v0.0.0-20191011191535-87dc89f01550"
    "golang.org/x/crypto v0.0.0-20191011191535-87dc89f01550/go.mod"
    "golang.org/x/mod v0.1.1-0.20191105210325-c90efee705ee/go.mod"
    "golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3/go.mod"
    "golang.org/x/net v0.0.0-20190620200207-3b0461eec859/go.mod"
    "golang.org/x/net v0.0.0-20190923162816-aa69164e4478"
    "golang.org/x/net v0.0.0-20190923162816-aa69164e4478/go.mod"
    "golang.org/x/sync v0.0.0-20190423024810-112230192c58"
    "golang.org/x/sync v0.0.0-20190423024810-112230192c58/go.mod"
    "golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a/go.mod"
    "golang.org/x/sys v0.0.0-20190412213103-97732733099d/go.mod"
    "golang.org/x/sys v0.0.0-20190924154521-2837fb4f24fe"
    "golang.org/x/sys v0.0.0-20190924154521-2837fb4f24fe/go.mod"
    "golang.org/x/text v0.3.0/go.mod"
    "golang.org/x/tools v0.0.0-20191216052735-49a3e744a425/go.mod"
    "golang.org/x/xerrors v0.0.0-20191011141410-1b5146add898/go.mod"
)
go-module_set_globals

if [[ ${PV} != *9999* ]]; then
    SRC_URI="https://github.com/zhoreeq/${PN}/archive/v${PV}.tar.gz -> ${P}.tar.gz"
    KEYWORDS="amd64 ~amd64 x86 ~x86"
else
    EGIT_REPO_URI="https://github.com/zhoreeq/${PN}.git"
    KEYWORDS="amd64 x86"
fi
SRC_URI+="${EGO_SUM_SRC_URI}"

LICENSE="MIT"
SLOT="0"
IUSE="systemd"

DEPEND=">dev-lang/go-1.12"

src_install() {
    echo ""
    exeinto /usr/bin
    doexe meshnamed
    dodoc README.md protocol.md

    if use systemd ; then
        systemd_newunit "${PN}d.service" ${PN}d.service
    else
        newinitd "${FILESDIR}/${PN}d.initd" ${PN}d
    fi
}

pkg_postinst() {
    elog "The meshname config file must be generated before use:"
    elog "  # meshnamed -genconf <IPv6> -subdomain meshname | tee /etc/meshnamed.conf"
    elog
    elog "The meshname daemon will have to be started before use:"
    if use systemd ; then
        elog "  # systemctl start meshnamed"
    else
        elog "  # rc-service meshnamed start"
    fi
}
```

2) meshnamed.initd - сценарий службы для системы инициализации OpenRC/SysV/init:
```
#!/sbin/openrc-run
# Distributed under the terms of the GNU General Public License v2

extra_started_commands="reload"
command="/usr/bin/meshnamed"
description="Distributed naming system for IPv6 mesh networks"
pidfile="/run/meshnamed.pid"
logfile="/var/run/meshnamed.log"
start_stop_daemon_args="--user nobody --group nobody -listenaddr '[::1]:53535' -useconffile /etc/meshnamed.conf"

start() {
    ebegin "Starting Distributed naming system for IPv6 mesh networks"
    start-stop-daemon --start --exec "${command}" --pidfile "${pidfile}" --background \
    	--stdout "${logfile}" --stderr "${logfile}"
    eend $?
}

stop() {
    ebegin "Distributed naming system for IPv6 mesh networks"
    start-stop-daemon --stop --exec "${command}" --pidfile "${pidfile}"
    eend $?
}

reload() {
    stop
    sleep 5
    start
}
```

P.S. Программу можно легко добавить в каталог программ Gentoo. Но вначале желательно определиться, будет ли init-скрипт для openrc в твоих исходниках, или его предстоит добавить в каталог Gentoo (там необходимо подправить ebuild).
Было бы культурно, если бы ebuild был добавлен самим автором, а не мной (чтобы отчёты летели на email автора, а не мне).

**Comment by Bogdan107** [comment]
ebuild добавлен в portage: https://bugs.gentoo.org/787092
После модерации должен появиться в каталоге.

**Comment by zhoreeq** [comment]
@Bogdan107 круто, спасибо! [Написал в тележке](https://t.me/PopuraChan/87)

**Comment by Bogdan107** [comment]
Я был бы очень рад. чтобы init-файл был включён в исходники программы и поддерживался автором программы, а ebuild распространялся бы только как скрипт сборки, без зависимостей (вроде файла инициализации).

**Comment by Bogdan107** [comment]
Админы каталога ищут для пакета маинтейнера - того, кто будет поддерживать ebuild (отвечать за актуальность - обновлять версии, решать баги совместимости и т.п.).
Без маинтейнера могут не пропустить ebuild.

Если есть идеи на счёт ответственного за ebuild в каталоге Gentoo, то сейчас - самое время их реализовать (кто-то, кто дружит с Gentoo и имеет тесную связь с разработчиком meshname).

**Comment by dm9pZCAq** [comment]
@Bogdan107
сейчас новые пакеты в основной оверлей `::gentoo` не принимаются из-за недостатка мейнтейнеров, по этому обычно такие пакеты добавляют в [::guru](https://wiki.gentoo.org/wiki/Project:GURU) 

и кстати в `meshnamed.initd` нужно поменять `--group nobody` на `nogroup`


@zhoreeq 
а я пока добавил `meshname` в свой [оверлей](https://github.com/gentoo-mirror/dm9pZCAq) и слежу за релизами в [rss](https://github.com/zhoreeq/meshname/releases.atom)

вот инструкция для `README` или еще чего то:
```sh
eselect repository enable dm9pZCAq
emerge --sync dm9pZCAq
emerge net-dns/meshname::dm9pZCAq
```
