### ISSUE TITLE
DNS server is not responding

### ISSUE THREAD

**Issue by marek22k** [zhoreeq/meshname#17]
Hello, I recently installed Mesh Name or compiled it myself. Now I am faced with the problem that nothing happens when I make a request.
Start with: ```./meshnamed -listenaddr 127.0.0.1:12345```
Request try 1:
```
$dig -p 12345 @127.0.0.1 aiaprmpzoslh7xjscrorzqbwpe.meshname AAAA

; <<>> DiG 9.16.22-Debian <<>> -p 12345 @127.0.0.1 aiaprmpzoslh7xjscrorzqbwpe.meshname AAAA
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39809
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;aiaprmpzoslh7xjscrorzqbwpe.meshname. IN	AAAA

;; Query time: 4999 msec
;; SERVER: 127.0.0.1#12345(127.0.0.1)
;; WHEN: Tue Jan 04 18:23:49 CET 2022
;; MSG SIZE  rcvd: 53
```
Request try 2:
```
$dig -p 12345 @127.0.0.1 aiaprmpzoslh7xjscrorzqbwpe.meship AAAA

; <<>> DiG 9.16.22-Debian <<>> -p 12345 @127.0.0.1 aiaprmpzoslh7xjscrorzqbwpe.meship AAAA
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21412
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;aiaprmpzoslh7xjscrorzqbwpe.meship. IN	AAAA

;; ANSWER SECTION:
aiaprmpzoslh7xjscrorzqbwpe.meship. 3600	IN AAAA	200:f8b1:f974:967f:dd32:145d:1cc0:3679

;; Query time: 0 msec
;; SERVER: 127.0.0.1#12345(127.0.0.1)
;; WHEN: Tue Jan 04 18:26:47 CET 2022
;; MSG SIZE  rcvd: 112
```

Somehow the non-existent TLD .meship seems to work to me. In this case, however, it does not resolve to the correct IP address.
.meshname doesn't work at all.

I tried the following mesh name domain / IP address:
```
aisaohridkpnggzcv7rerltohy.meshname		324:71e:281a:9ed3::ace
```

Is that ahead? How can I fix the problem?

**Comment by zhoreeq** [comment]
I think that particular domain is down. Try resolving `aikqcxee4cg5k5mqx7gwdt6p64.meshname`

**Comment by marek22k** [comment]
That's working. Thank you. But why does one and the other not work? As I understood meshname, it's just a (base32) encoding for IPv6 addresses, isn't it? So you should be able to dissolve each one, right? For example, I can create an address aaaaaaaaaaaaaaaaaaaaaaaaae.meshname for my localhost :: 1, but this is also not resolved. Which creterium must meshname addresses meet in order to be resolved?

**Edit:** I have now read the protocol.md again more closely. I understand it now. Is there a provider for such a name server or do you have to operate it yourself? Is there a directory of working mesh names (or a smaller list of working examples)?

**Comment by zhoreeq** [comment]
Yeah, that decoded IPv6 address is the nameserver responsible for that particular `<b32>.meshname` space. 

Your local meshnamed basically proxies DNS queries to the decoded IPv6 address.

>But why does one and the other not work? 

`200:f8b1:f974:967f:dd32:145d:1cc0:3679` is down, so meshnamed can't connect to it and fails to resolve the `aiaprmpzoslh7xjscrorzqbwpe.meshname` domain.

>Is there a provider for such a name server or do you have to operate it yourself? 

You have to operate a nameserver yourself, everybody is responsible for their own domain space. That way there is no centralization, which is the main point of the system. :-)

>Is there a directory of working mesh names (or a smaller list of working examples)?

Not that I know of. 

Try these

```
aikqcxee4cg5k5mqx7gwdt6p64.meshname   
xmpp.aikqcxee4cg5k5mqx7gwdt6p64.meshname   
squid-game.aikqcxee4cg5k5mqx7gwdt6p64.meshname 
```

acetone's domains don't resolve currently (must be server configuration issues)

```
aisaohridkpnggzcv7rerltohy.meshname		324:71e:281a:9ed3::ace
mumble.aisaohridkpnggzcv7rerltohy.meshname	324:71e:281a:9ed3::cafe
irc.aisaohridkpnggzcv7rerltohy.meshname		324:71e:281a:9ed3::41
```

**Comment by marek22k** [comment]
Many thanks for the answer!
