### ISSUE TITLE
Adding the Ruby library meshname

### ISSUE THREAD

**Issue by marek22k** [zhoreeq/meshname#18]
Hello,

I don't know if this is the right place for this. So sorry if I'm rude.
I wrote a little Ruby library for Meshname:
https://rubygems.org/gems/meshname
https://github.com/marek22k/meshname
The library implements "meshnamed -getip" and "meshnamed -getname". As well as resolving .meshname and .meship domains.
Documentation can be found on https://www.rubydoc.info/github/marek22k/meshname/Meshname

Maybe you could link to it somewhere or in the wiki?

A little more script, you can make a server: https://gist.github.com/marek22k/795b7e1b9e2dcd5df46ee601f566058e

**Comment by zhoreeq** [comment]
Great lib, thanks! I will add it to the README file :-)

**Comment by zhoreeq** [comment]
Added in 38781e3
