### ISSUE TITLE
"localhost" and other reserved aliases for meshname

### ISSUE THREAD

**Issue by Saiv46** [zhoreeq/meshname#5]
I suggest adding some special meshname domains:
- `local.meshname.` matching every local IP (localhost).
- `test.meshname` is a special domain, whose destination is implementation-defined (ex. option for `meshnamed`).
- `example.meshname.` is for documentation purposes.

**Comment by zhoreeq** [comment]
Interesting ideas. Do you propose to add those special domains to the protocol specification? Are there any other RFCs/protocol specs doing something similar? 

Also, think about what value does it provide  to users VS how much complexity will that add. Maybe it's better to keep the spec minimal, if it's not absolutely necessary to do the main job.

**Comment by Saiv46** [comment]
> Interesting ideas. Do you propose to add those special domains to the protocol specification? Are there any other RFCs/protocol specs doing something similar?

RFC 2506: https://tools.ietf.org/html/rfc2606

**Comment by acetoneRu** [comment]
`*.meship` for simple convertation domain->address and address->domain without all meshname backend logic (only base32 encoding).
