### ISSUE TITLE
Setup wizard helper

### ISSUE THREAD

**Issue by ghost** [zhoreeq/meshname#6]
Can u add a script (or graphical application) to easily install meshname. And also cross-platform support (Windows, Android, IOS, MacOS)

**Comment by zhoreeq** [comment]
Нужно тогда написать setup_wizard.sh для Ubuntu и Debian Linux.

Этот скрипт должен:

- предложить автоматически скачать и установить все файлы для текущей платформы, либо использовать самостоятельно собранный бинарник
- запустить systemd службу
- предложить установить dnsmasq, если не установлен
- прописать dnsmasq как системный резолвер
    - тут надо проверить наличие всяких networkmanager и systemd-resolved
- сгенерировать конфиги для meshname и dnsmasq
    -  тут надо определить ygg0 или tun0 интерфейс и получить его IPv6 адрес
- сделать рекомендации по открытию порта в firewall'е
- показать пример добавления различных DNS записей для `meshname.conf`
- отдельно должна быть логика для режима с Popura

**Comment by zhoreeq** [comment]
Теперь вместо всей этой суеты с мешнеймом и dnsmasq лучше использовать [vapordns](https://github.com/popura-network/vapordns)
